theme: jekyll-theme-cayman

repository: emerging-architectures/sciml_benchmarks

show_logo: true
show_description: false
show_github: true
show_downloads: false

nrl:
  url: https://www.nrl.navy.mil/
  lcp:
    url: https://www.nrl.navy.mil/lcp/
  logo:
    color: /assets/images/nrl/logo_color.png
    white: /assets/images/nrl/logo_white.png

markdown: kramdown
